### ISSUE TITLE
3.0.0b6:Failed to load my deebot.

### ISSUE THREAD

**Issue by cloudicen** [And3rsL/Deebot-for-Home-Assistant#140] opened 2021-06-18 12:42 UTC
**Describe the bug**
After updating from 2.1.2 to 3.0.0b6, an error occurred. 
![image](https://user-images.githubusercontent.com/36070534/122561475-7b660780-d074-11eb-958a-cd993edf640a.png)

vacuum:
  - platform: deebot
    username: ECUFCH9A
    password: 12345678
    country: cn
    continent: as
```

**System Informations:**
 - Device: Deebot T8
 - Home Assistant Version: core-2021.6.4
 - Hardware: Cloud Server
 - Home Assistant Installation: Linux Docker

**Logs**
2021-06-18 20:23:48 DEBUG (MainThread) [deebotozmo.ecovacs_api] Start login to EcovacsAPI
2021-06-18 20:23:48 DEBUG (MainThread) [deebotozmo.ecovacs_api] calling login api
2021-06-18 20:23:49 DEBUG (MainThread) [deebotozmo.ecovacs_api] got {'code': '0000', 'msg': '操作成功', 'time': 1624019029422, 'data': {'uid': '20200120164613_4dd0f2b1dd0b3c37905c5bda039d1a9d', 'accessToken': 'cab9032259ee0a498b793e01e0b6e441', 'userName': 'ECUFCH9A', 'email': None, 'mobile': '+86-18850779113', 'isNew': None, 'loginName': '18850779113', 'ucUid': '20200120164135_e0b33e26f49de46e7ff4cbc3970466a1'}, 'success': True}
2021-06-18 20:23:49 DEBUG (MainThread) [deebotozmo.ecovacs_api] calling auth api
2021-06-18 20:23:49 DEBUG (MainThread) [deebotozmo.ecovacs_api] got {'code': '0000', 'msg': '操作成功', 'time': 1624019029491, 'data': {'authCode': 'GLOBAL_APP_ECOVACS_IOT_a4328c4c536f847c962f955a8a8e8c0a', 'ecovacsUid': '20200120164135_e0b33e26f49de46e7ff4cbc3970466a1'}, 'success': True}
2021-06-18 20:23:49 DEBUG (MainThread) [deebotozmo.ecovacs_api] calling user api users/user.do with {'edition': 'ECOGLOBLE', 'userId': '20200120164613_4dd0f2b1dd0b3c37905c5bda039d1a9d', 'token': 'GLOBAL_APP_ECOVACS_IOT_a4328c4c536f847c962f955a8a8e8c0a', 'realm': 'ecouser.net', 'resource': 'XPFW3Q4B', 'org': 'ECOCN', 'last': '', 'country': 'Chinese', 'todo': 'loginByItToken'}
2021-06-18 20:23:49 DEBUG (MainThread) [deebotozmo.ecovacs_api] got {'todo': 'result', 'result': 'fail', 'errno': 1202, 'error': 'invalid org'}
2021-06-18 20:23:49 ERROR (MainThread) [deebotozmo.ecovacs_api] call to users/user.do failed with {'todo': 'result', 'result': 'fail', 'errno': 1202, 'error': 'invalid org'}

**Comment by cloudicen** [comment] 2021-06-18 12:48
when I try to add new Deebot integration. It shows an ‘Unknow Error’ through frontend like this：
![image](https://user-images.githubusercontent.com/36070534/122562911-29be7c80-d076-11eb-9cbc-3fbff7c507b1.png)



Witch is similar to https://github.com/And3rsL/Deebot-for-Home-Assistant/issues/139#issue-924815627

**Comment by edenhaus** [comment] 2021-06-18 13:52
Duplicate of #139

**Closed by edenhaus** 2021-06-18 13:52 UTC
Labels: bug
