### ISSUE TITLE
Empty the dust bin command

### ISSUE THREAD

**Issue by marcomow** [And3rsL/Deebot-for-Home-Assistant#155] opened 2021-07-15 17:14 UTC
**Is your feature request related to a problem? Please describe.**
I have an Ecovacs Deebot N8 PRO+ with auto-empty dust bin; "Empty the dust bin" functionality is available in the app, so it should be possible.

**Describe the solution you'd like**
Having a command to programmatically call this service.

**Describe alternatives you've considered**
Another possibility could be being able to toggle the setting, still a functionality available through the app but not yet in this integration.

**Additional context**
Great work, it would be awesome to have this feature implemented!

**Comment by edenhaus** [comment] 2021-07-16 08:31
Duplicate of #147 

Please check next time the open issues before opening a new one

**Closed by edenhaus** 2021-07-16 08:31 UTC
Labels: enhancement
